version: '3'

services:

  telegram_bot:
    build: .
    restart: always
    environment:
      BOT_API_TOKEN: ${BOT_API_TOKEN} 
      ADMIN_IDS: ${ADMIN_IDS} 
      SERVICE_GROUP_ID: ${SERVICE_GROUP_ID} 
      ERROR_TOPIC: ${ERROR_TOPIC} 
      INFO_TOPIC: ${INFO_TOPIC} 
      NEW_RECORDS_TOPIC: ${NEW_RECORDS_TOPIC} 
      DB_NAME: ${DB_NAME} 
      DB_USERNAME: ${DB_USERNAME} 
      DB_PASSWORD: ${DB_PASSWORD} 
      DB_HOST: ${DB_HOST} 
      DB_PORT: ${DB_PORT} 
    networks:
      - mynetwork
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - mynetwork

networks:
  mynetwork: