name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install sshpass
        run: sudo apt-get install sshpass
      - name: Send signal to VM
        run: sshpass -p $VM_PASSWORD ${{ vars.VM_USERNAME }}@${{ vars.VM_IP }} 'bash -s' < ./scripts/deploy.sh